-- Create the Users table
CREATE TABLE Users (
    UserID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserName TEXT NOT NULL,
    UserOrganization TEXT NOT NULL,
    UserEmail TEXT UNIQUE NOT NULL
);

-- Create the UserCredentials table for secure password storage
CREATE TABLE UserCredentials (
    UserID BIGINT PRIMARY KEY,
    PasswordHash TEXT NOT NULL,
    PasswordSalt TEXT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

-- Create the Organizations table
CREATE TABLE Organizations (
    OrganizationID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrganizationName TEXT NOT NULL UNIQUE,
    OrganizationType TEXT,
    AdminName TEXT NOT NULL,
    AdminEmail TEXT NOT NULL,
    AllottedUsers INTEGER DEFAULT 0,
    DateAdded TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    LastModified TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Optional: Create a table for password reset tokens
CREATE TABLE PasswordResetTokens (
    TokenID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID BIGINT NOT NULL,
    Token TEXT UNIQUE NOT NULL,
    ExpiresAt TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);