-- Create the Users table
CREATE TABLE Users (
    UserID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserName TEXT NOT NULL,
    UserOrganization TEXT NOT NULL,
    UserEmail TEXT UNIQUE NOT NULL
);

-- Create the UserCredentials table for secure password storage
CREATE TABLE UserCredentials (
    UserID BIGINT PRIMARY KEY,
    PasswordHash TEXT NOT NULL,
    PasswordSalt TEXT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

-- Ensure Users table has OrganizationID and UserType columns
ALTER TABLE IF EXISTS Users
ADD COLUMN IF NOT EXISTS OrganizationID BIGINT,
ADD COLUMN IF NOT EXISTS UserType TEXT;

-- Add FK to public.organizations(id) if not already present
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints tc
        WHERE tc.constraint_type = 'FOREIGN KEY'
          AND tc.table_schema = 'public'
          AND tc.table_name = 'users'
          AND tc.constraint_name = 'users_organizationid_fkey'
    ) THEN
        ALTER TABLE public.users
        ADD CONSTRAINT users_organizationid_fkey
        FOREIGN KEY (organizationid) REFERENCES public.organizations(id) ON DELETE SET NULL;
    END IF;
END$$;

-- Create the Organizations table
CREATE TABLE Organizations (
    OrganizationID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrganizationName TEXT NOT NULL UNIQUE,
    OrganizationType TEXT,
    AdminName TEXT NOT NULL,
    AdminEmail TEXT NOT NULL,
    AllottedUsers INTEGER DEFAULT 0,
    DateAdded TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    LastModified TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Optional: Create a table for password reset tokens
CREATE TABLE PasswordResetTokens (
    TokenID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID BIGINT NOT NULL,
    Token TEXT UNIQUE NOT NULL,
    ExpiresAt TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

-- =============================================================
-- Core table used by the frontend: public.organizations
-- Matches admin portal expectations: id, name, type, admin_email, users_allotted
-- =============================================================
CREATE TABLE IF NOT EXISTS public.organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    type TEXT,
    admin_email TEXT NOT NULL,
    users_allotted INTEGER NOT NULL DEFAULT 0,
    date_added TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_modified TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Trigger to keep last_modified current
CREATE OR REPLACE FUNCTION public.set_last_modified()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.last_modified := NOW();
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS organizations_set_last_modified ON public.organizations;
CREATE TRIGGER organizations_set_last_modified
BEFORE UPDATE ON public.organizations
FOR EACH ROW EXECUTE FUNCTION public.set_last_modified();

-- Enable Row Level Security and add simple anon policies for testing
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public' AND tablename = 'organizations' AND policyname = 'anon insert'
    ) THEN
        CREATE POLICY "anon insert"
        ON public.organizations
        FOR INSERT
        TO anon
        WITH CHECK (TRUE);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public' AND tablename = 'organizations' AND policyname = 'anon select'
    ) THEN
        CREATE POLICY "anon select"
        ON public.organizations
        FOR SELECT
        TO anon
        USING (TRUE);
    END IF;
END$$;